<div class="customers_show">
    <div class="customers_show_title">
        <h3>D-daydress's Customers Show</h3>
    </div>
    <span>* Share your look to get $15 discount!</span>
    <div class="customers_show_photo owl-carousel">
        <div class="item"><a href="">1</a></div>
        <div class="item"><a href="">2</a></div>
        <div class="item"><a href="">3</a></div>
        <div class="item"><a href="">4</a></div>
        <div class="item"><a href="">5</a></div>
        <div class="item"><a href="">6</a></div>
        <div class="item"><a href="">7</a></div>
    </div>
    <div class="btn_div upload_a_photo">
        <em></em>UPLOAD A PHOTO
    </div>
    <div class="btn_div view_gallery">
        <em></em>VIEW GALLERY
    </div>
</div>